server:
    port: 8085

spring:
    application:
        name: GatewayService
    cloud:
        gateway:
            routes:
              - id: ORDER-SERVICE
                uri: lb://ORDER-SERVICE
                predicates:
                   - Path=/orders/**
                filters:
                   - name: CircuitBreaker
                     args:
                       name: ORDER-SERVICE
                       fallbackuri: forward:/orderFallBack
              - id: PAYMENT-SERVICE
                uri: lb://PAYMENT-SERVICE
                predicates:
                   - Path=/payment/**
                filters:
                   - name: CircuitBreaker
                     args:
                       name: PAYMENT-SERVICE
                       fallbackuri: forward:/paymentFallBack
        
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000